# Generated by Django 4.1.2 on 2022-11-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_video_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='user',
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='path',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
