# Generated by Django 4.1.3 on 2022-11-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_1", "0003_remove_video_user_alter_video_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="edad",
        ),
        migrations.AddField(
            model_name="video",
            name="duracion",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="thumnail",
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
