# Generated by Django 4.1.3 on 2022-11-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_1", "0005_rename_channel_name_comment_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="cathegory",
            field=models.CharField(
                choices=[
                    ("1", "COMIDA"),
                    ("2", "DEPORTE"),
                    ("3", "ENTRETENIMIENTO"),
                    ("4", "OCIO"),
                    ("5", "SERIE"),
                    ("6", "VIAJES"),
                    ("7", "BUSINESS"),
                ],
                max_length=300,
                null=True,
            ),
        ),
    ]
