# Generated by Django 4.2.dev20221024115451 on 2022-11-19 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0006_video_cathegory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='dateTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='video',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_1.video'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='video',
            name='cathegory',
            field=models.CharField(choices=[('1', 'COMIDA'), ('2', 'DEPORTE'), ('3', 'ENTRETENIMIENTO'), ('4', 'OCIO'), ('5', 'SERIE'), ('6', 'VIAJES'), ('7', 'BUSINESS')], default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='length',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default='', max_length=30),
        ),
    ]
