# Generated by Django 4.2.dev20221024115451 on 2022-12-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0015_delete_uploadvideo_video_file_video_thumnail1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='path',
            field=models.CharField(blank='True', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumnail',
            field=models.CharField(blank='True', max_length=2000, null=True),
        ),
    ]
